package claudemd

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/carsteneu/yesmem/internal/briefing"
	"github.com/carsteneu/yesmem/internal/config"
	"github.com/carsteneu/yesmem/internal/extraction"
	"github.com/carsteneu/yesmem/internal/models"
	"github.com/carsteneu/yesmem/internal/storage"
)

// Generator creates and updates yesmem-ops.md files per project.
type Generator struct {
	store  *storage.Store
	client extraction.LLMClient
	cfg    *config.ClaudeMdConfig
}

func NewGenerator(store *storage.Store, client extraction.LLMClient, cfg *config.ClaudeMdConfig) *Generator {
	return &Generator{store: store, client: client, cfg: cfg}
}

// Generate creates or updates the yesmem-ops.md for the given project.
// projectShort is the DB project key; projectDir is the filesystem path.
func (g *Generator) Generate(projectShort, projectDir string) error {
	// 1. Collect
	learnings, err := g.store.GetLearningsForClaudeMd(projectShort, g.cfg.MaxPerCategory)
	if err != nil {
		return fmt.Errorf("collect learnings: %w", err)
	}
	if len(learnings) == 0 {
		return fmt.Errorf("no learnings for project %q", projectShort)
	}

	// 2. Deduplicate
	learnings = briefing.Deduplicate(learnings, 0.4)

	// 3. Change detection
	hash := hashLearnings(learnings)
	state, err := g.store.GetClaudeMdState(projectShort)
	if err != nil {
		return fmt.Errorf("get state: %w", err)
	}
	if state != nil && state.LearningsHash == hash {
		return nil // nothing changed
	}

	// 4. Structure via LLM
	prompt, err := buildPrompt(projectShort, learnings)
	if err != nil {
		return err
	}
	content, err := g.client.Complete(systemPrompt, prompt)
	if err != nil {
		return fmt.Errorf("llm call: %w", err)
	}

	// 5. Write
	outputPath, err := g.write(projectDir, projectShort, content)
	if err != nil {
		return err
	}

	// 6. Save state
	return g.store.SaveClaudeMdState(&storage.ClaudeMdState{
		Project:       projectShort,
		LastGenerated: time.Now(),
		LearningsHash: hash,
		OutputPath:    outputPath,
	})
}

// NeedsRefresh checks if a project's file is stale.
func (g *Generator) NeedsRefresh(projectShort string) (bool, error) {
	state, err := g.store.GetClaudeMdState(projectShort)
	if err != nil {
		return false, err
	}
	if state == nil {
		return true, nil
	}
	learnings, err := g.store.GetLearningsForClaudeMd(projectShort, g.cfg.MaxPerCategory)
	if err != nil {
		return false, err
	}
	learnings = briefing.Deduplicate(learnings, 0.4)
	return hashLearnings(learnings) != state.LearningsHash, nil
}

func (g *Generator) write(projectDir, projectShort, content string) (string, error) {
	if _, err := os.Stat(projectDir); os.IsNotExist(err) {
		return "", fmt.Errorf("project dir does not exist: %s", projectDir)
	}
	dotClaude := filepath.Join(projectDir, ".claude")
	if err := os.MkdirAll(dotClaude, 0755); err != nil {
		return "", fmt.Errorf("create .claude dir: %w", err)
	}
	outputFile := g.cfg.OutputFileName
	if outputFile == "" {
		outputFile = "yesmem-ops.md"
	}
	outPath := filepath.Join(dotClaude, outputFile)
	header := fmt.Sprintf("# Operational Notes — %s\n> Auto-generated by yesmem (%s)\n> Do not edit manually — will be overwritten on changes\n\n",
		projectShort, time.Now().Format("2006-01-02 15:04"))
	return outPath, os.WriteFile(outPath, []byte(header+strings.TrimSpace(content)+"\n"), 0644)
}

func hashLearnings(learnings []models.Learning) string {
	h := sha256.New()
	for _, l := range learnings {
		fmt.Fprintf(h, "%d:%s\n", l.ID, l.Content)
	}
	return fmt.Sprintf("%x", h.Sum(nil))[:16]
}
